baseurl: http://jamie-wong.com
disablePathToLower: true
languageCode: en-us
title: 'Zero Wind :: Jamie Wong'
PygmentsCodeFences: true
pygmentsuseclasses: true
toctoken: "{:toc}"
disableRSS: false
rssuri: atom.xml
blackfriday:
    extensions:
        - laxHtmlBlocks
...
