# standard jekyll configuration

permalink: pretty
pygments: false
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: jamie-wong.com
title: "Zero Wind :: Jamie Wong"
author: Jamie Wong
email: jamie.lf.wong@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
